### ISSUE TITLE
file 命令报错

### ISSUE THREAD

**Issue by toyops** [shaowenchen/ops#2]
client.Dial failed 192.168.1.2: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
client.Dial failed 192.168.1.2: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

shell 命令可以顺利执行，file 无法执行 upload

**Comment by shaowenchen** [comment]
可以输出 opscli file -h  看看参数，上面的报错看起来是没有设置 password 或 privatekeypath

**Comment by toyops** [comment]
> 可以输出 opscli file -h 看看参数，上面的报错看起来是没有设置 password 或 privatekeypath

……如果我没带这个参数的话，我 shell 命令应该无法执行了，而且我使用 task 中的 file 指令也是无法执行的。

又试了下shell 命令是可以的。task 里面也无法执行。发行版都是 centos7
`[root@vm task]$opscli shell -i 192.168.1.99 --password 'pw123' --content "uname -a"
> Run Shell on  192.168.1.99
Linux sz123 5.15.91-bbrplus.el7.x86_64 #1 SMP Sat Feb 4 05:21:09 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
[root@vm task]$cat shell.yml
apiVersion: crd.chenshaowen.com/v1
kind: Task
metadata:
  name: task-sample
  namespace: ops-system
spec:
  desc: uname
  steps:
    - name: uname
      content: uname -a
[root@vm task]$opscli task -f shell.yml -i 192.168.1.99 --password pw123
client.Dial failed 192.168.1.99: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password publickey], no supported methods remain`

**Comment by shaowenchen** [comment]
确实有问题，file、task 使用 password 验证时，需要带 username 才行。我马上修复一下，抱歉了

**Comment by shaowenchen** [comment]
> > 可以输出 opscli file -h 看看参数，上面的报错看起来是没有设置 password 或 privatekeypath
> 
> ……如果我没带这个参数的话，我 shell 命令应该无法执行了，而且我使用 task 中的 file 指令也是无法执行的。
> 
> 又试了下shell 命令是可以的。task 里面也无法执行。发行版都是 centos7 `[root@vm task]$opscli shell -i 192.168.1.99 --password 'pw123' --content "uname -a"
> 
> > Run Shell on  192.168.1.99
> > Linux sz123 5.15.91-bbrplus.el7.x86_64 #1 SMP Sat Feb 4 05:21:09 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
> > [root@vm task]$cat shell.yml
> > apiVersion: crd.chenshaowen.com/v1
> > kind: Task
> > metadata:
> > name: task-sample
> > namespace: ops-system
> > spec:
> > desc: uname
> > steps:
> > - name: uname
> > content: uname -a
> > [root@vm task]$opscli task -f shell.yml -i 192.168.1.99 --password pw123
> > client.Dial failed 192.168.1.99: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password publickey], no supported methods remain`

你好，已经修复这个问题，请执行 `opscli upgrade` 升级版本即可。现在 file、task 会默认使用当前用户作为远程的 username。

```bash
 opscli version

{"Version":"latest","BuildDate":"2023-09-21T12:13:18Z","GitCommit":"c2a13df"}
```

**Comment by toyops** [comment]
> > > 可以输出 opscli file -h 看看参数，上面的报错看起来是没有设置 password 或 privatekeypath
> > 
> > 
> > ……如果我没带这个参数的话，我 shell 命令应该无法执行了，而且我使用 task 中的 file 指令也是无法执行的。
> > 又试了下shell 命令是可以的。task 里面也无法执行。发行版都是 centos7 `[root@vm task]$opscli shell -i 192.168.1.99 --password 'pw123' --content "uname -a"
> > > Run Shell on  192.168.1.99
> > > Linux sz123 5.15.91-bbrplus.el7.x86_64 #1 SMP Sat Feb 4 05:21:09 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
> > > [root@vm task]$cat shell.yml
> > > apiVersion: crd.chenshaowen.com/v1
> > > kind: Task
> > > metadata:
> > > name: task-sample
> > > namespace: ops-system
> > > spec:
> > > desc: uname
> > > steps:
> > > 
> > > * name: uname
> > >   content: uname -a
> > >   [root@vm task]$opscli task -f shell.yml -i 192.168.1.99 --password pw123
> > >   client.Dial failed 192.168.1.99: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password publickey], no supported methods remain`
> 
> 你好，已经修复这个问题，请执行 `opscli upgrade` 升级版本即可。现在 file、task 会默认使用当前用户作为远程的 username。
> 
> ```shell
>  opscli version
> 
> {"Version":"latest","BuildDate":"2023-09-21T12:13:18Z","GitCommit":"c2a13df"}
> ```

好的，感谢，我也是有点惯性思维了。
